<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class motoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $horaActual = Carbon::now();

        DB::table('motos')->insert([
            'modelo_id' => 1,
            'tipo_moto_id' => 4,
            'año' => 2024,
            'precio_base' => 3500.00,
            'color' => 'Negro',
            'stock' => 10,
            'descripcion' => 'MM CALI NEGRO',
            'imagen' => 'assets/imagen/motos/MM_CALI_NEGRO_1.png',
            'cilindrada' => 150.0,
            'motor' => '4 tiempos OHC',
            'potencia' => '15 HP a 8500 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '5 velocidades',
            'capacidad_tanque' => 12.5,
            'peso_neto' => 120,
            'carga_util' => 150,
            'peso_bruto' => 270,
            'largo' => 2000,
            'ancho' => 800, 
            'alto' => 1100,
            'neumatico_delantero' => '90/90-17',
            'neumatico_posterior' => '120/80-17',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Tambor',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => false,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 2,
            'tipo_moto_id' => 4,
            'año' => 2024,
            'precio_base' => 4200.00,
            'color' => 'Blanco',
            'stock' => 8,
            'descripcion' => 'MM CALI BLANCO',
            'imagen' => 'assets/imagen/motos/MM_CALI_BLANCO_1.png',
            'cilindrada' => 125.0,
            'motor' => '4 tiempos SOHC',
            'potencia' => '12 HP a 8000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => 'Automática CVT',
            'capacidad_tanque' => 6.5,
            'peso_neto' => 95,
            'carga_util' => 130,
            'peso_bruto' => 225,
            'largo' => 1850,
            'ancho' => 700,
            'alto' => 1050,
            'neumatico_delantero' => '80/90-14',
            'neumatico_posterior' => '100/90-14',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => true,
            'tablero_led' => true,
            'mp3' => true,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 3,
            'tipo_moto_id' => 4,
            'año' => 2024,
            'precio_base' => 5500.00,
            'color' => 'Rojo',
            'stock' => 5,
            'descripcion' => 'MM CALI ROJO',
            'imagen' => 'assets/imagen/motos/MM_CALI_ROJO_1.png',
            'cilindrada' => 250.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '25 HP a 9000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 15.0,
            'peso_neto' => 145,
            'carga_util' => 170,
            'peso_bruto' => 315,
            'largo' => 2200,
            'ancho' => 850,
            'alto' => 1250,
            'neumatico_delantero' => '90/90-21',
            'neumatico_posterior' => '120/90-18',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 4,
            'tipo_moto_id' => 3,
            'año' => 2024,
            'precio_base' => 2800.00,
            'color' => 'Negro Rojo',
            'stock' => 15,
            'descripcion' => 'ALASKA 250 COSTADO DERECHO',
            'imagen' => 'assets/imagen/motos/ALASKA-250_COSTADO-DERECHO.png',
            'cilindrada' => 110.0,
            'motor' => '4 tiempos OHC',
            'potencia' => '8.5 HP a 7500 rpm',
            'arranque' => 'Eléctrico y Pedal',
            'transmision' => '4 velocidades',
            'capacidad_tanque' => 4.5,
            'peso_neto' => 85,
            'carga_util' => 120,
            'peso_bruto' => 205,
            'largo' => 1800,
            'ancho' => 650,
            'alto' => 1000,
            'neumatico_delantero' => '70/90-17',
            'neumatico_posterior' => '80/90-17',
            'freno_delantero' => 'Tambor',
            'freno_posterior' => 'Tambor',
            'cargador_usb' => false,
            'luz_led' => false,
            'alarma' => false,
            'cajuela' => false,
            'tablero_led' => false,
            'mp3' => false,
            'bluetooth' => false,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 5,
            'tipo_moto_id' => 3,
            'año' => 2024,
            'precio_base' => 7500.00,
            'color' => 'Negro Rojo',
            'stock' => 8,
            'descripcion' => 'ALASKA 250 DIAGONAL DERECHO',
            'imagen' => 'assets/imagen/motos/ALASKA-250_DIAGONAL-DERECHO.png',
            'cilindrada' => 600.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '100 HP a 12000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 17.0,
            'peso_neto' => 190,
            'carga_util' => 180,
            'peso_bruto' => 370,
            'largo' => 2100,
            'ancho' => 730,
            'alto' => 1150,
            'neumatico_delantero' => '120/70-17',
            'neumatico_posterior' => '180/55-17',
            'freno_delantero' => 'Disco doble',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 6,
            'tipo_moto_id' => 1,
            'año' => 2024,
            'precio_base' => 4200.00,
            'color' => 'Celeste',
            'stock' => 12,
            'descripcion' => 'CHEYENNE CELeste',
            'imagen' => 'assets/imagen/motos/cheyenne-celeste.png',
            'cilindrada' => 150.0,
            'motor' => '4 tiempos OHC',
            'potencia' => '15 HP a 8000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => 'Automática CVT',
            'capacidad_tanque' => 7.0,
            'peso_neto' => 110,
            'carga_util' => 150,
            'peso_bruto' => 260,
            'largo' => 1900,
            'ancho' => 700,
            'alto' => 1150,
            'neumatico_delantero' => '100/80-14',
            'neumatico_posterior' => '120/70-14',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Tambor',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => true,
            'tablero_led' => true,
            'mp3' => true,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 7,
            'tipo_moto_id' => 1,
            'año' => 2024,
            'precio_base' => 6800.00,
            'color' => 'Celeste',
            'stock' => 6,
            'descripcion' => 'CHEYENNE COSTADO CELeste',
            'imagen' => 'assets/imagen/motos/cheyenne-costado-celeste.png',
            'cilindrada' => 450.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '45 HP a 9500 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 18.0,
            'peso_neto' => 160,
            'carga_util' => 180,
            'peso_bruto' => 340,
            'largo' => 2300,
            'ancho' => 900,
            'alto' => 1400,
            'neumatico_delantero' => '90/90-21',
            'neumatico_posterior' => '130/90-18',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 8,
            'tipo_moto_id' => 1,
            'año' => 2024,
            'precio_base' => 9500.00,
            'color' => 'Negro Rojo',
            'stock' => 4,
            'descripcion' => 'cheyenne',
            'imagen' => 'assets/imagen/motos/cheyenne.png',
            'cilindrada' => 1000.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '180 HP a 13000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 16.0,
            'peso_neto' => 200,
            'carga_util' => 190,
            'peso_bruto' => 390,
            'largo' => 2080,
            'ancho' => 750,
            'alto' => 1145,
            'neumatico_delantero' => '120/70-17',
            'neumatico_posterior' => '190/55-17',
            'freno_delantero' => 'Disco doble',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 9,
            'tipo_moto_id' => 1,
            'año' => 2024,
            'precio_base' => 3200.00,
            'color' => 'Rojo',
            'stock' => 20,
            'descripcion' => 'cheyenne costado rojo',
            'imagen' => 'assets/imagen/motos/cheyenne-costado-rojo.png',
            'cilindrada' => 125.0,
            'motor' => '4 tiempos OHC',
            'potencia' => '12 HP a 8000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '5 velocidades',
            'capacidad_tanque' => 5.5,
            'peso_neto' => 95,
            'carga_util' => 130,
            'peso_bruto' => 225,
            'largo' => 1850,
            'ancho' => 680,
            'alto' => 1050,
            'neumatico_delantero' => '80/90-17',
            'neumatico_posterior' => '90/90-17',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Tambor',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => false,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 10,
            'tipo_moto_id' => 1,
            'año' => 2024,
            'precio_base' => 4500.00,
            'color' => 'Celeste',
            'stock' => 15,
            'descripcion' => 'CELESTE_DIAGONAL_DERECHO',
            'imagen' => 'assets/imagen/motos/CELESTE_DIAGONAL_DERECHO.png',
            'cilindrada' => 200.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '24 HP a 9500 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 12.0,
            'peso_neto' => 140,
            'carga_util' => 150,
            'peso_bruto' => 290,
            'largo' => 2000,
            'ancho' => 720,
            'alto' => 1100,
            'neumatico_delantero' => '100/80-17',
            'neumatico_posterior' => '130/70-17',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => true,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 1,
            'tipo_moto_id' => 1,
            'año' => 2024,
            'precio_base' => 5800.00,
            'color' => 'Naranja',
            'stock' => 8,
            'descripcion' => 'NARANJA DIAGONAL DERECHO',
            'imagen' => 'assets/imagen/motos/NARANJA_DIAGONAL_DERECHO.png',
            'cilindrada' => 250.0,
            'motor' => '4 tiempos OHC',
            'potencia' => '30 HP a 9000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 13.0,
            'peso_neto' => 155,
            'carga_util' => 170,
            'peso_bruto' => 325,
            'largo' => 2200,
            'ancho' => 850,
            'alto' => 1250,
            'neumatico_delantero' => '90/90-21',
            'neumatico_posterior' => '120/90-18',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => true,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 2,
            'tipo_moto_id' => 5,
            'año' => 2024,
            'precio_base' => 7200.00,
            'color' => 'Naranja',
            'stock' => 12,
            'descripcion' => 'DAKOTA NARANJA',
            'imagen' => 'assets/imagen/motos/DAKOTA-NARANJA.png',
            'cilindrada' => 400.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '45 HP a 10000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 14.0,
            'peso_neto' => 170,
            'carga_util' => 180,
            'peso_bruto' => 350,
            'largo' => 2050,
            'ancho' => 730,
            'alto' => 1150,
            'neumatico_delantero' => '110/70-17',
            'neumatico_posterior' => '150/60-17',
            'freno_delantero' => 'Disco doble',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => true,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 3,
            'tipo_moto_id' => 5,
            'año' => 2024,
            'precio_base' => 2800.00,
            'color' => 'Naranja',
            'stock' => 25,
            'descripcion' => 'DAKOTA NARANJA COSTADP',
            'imagen' => 'assets/imagen/motos/DAKOTA-NARANJA-COSTADP.png',
            'cilindrada' => 110.0,
            'motor' => '4 tiempos OHC',
            'potencia' => '8.5 HP a 7500 rpm',
            'arranque' => 'Eléctrico/Pedal',
            'transmision' => '4 velocidades',
            'capacidad_tanque' => 4.5,
            'peso_neto' => 85,
            'carga_util' => 120,
            'peso_bruto' => 205,
            'largo' => 1800,
            'ancho' => 650,
            'alto' => 1000,
            'neumatico_delantero' => '70/90-17',
            'neumatico_posterior' => '80/90-17',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Tambor',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => true,
            'tablero_led' => false,
            'mp3' => false,
            'bluetooth' => false,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 4,
            'tipo_moto_id' => 5,
            'año' => 2024,
            'precio_base' => 4800.00,
            'color' => 'Rojo',
            'stock' => 10,
            'descripcion' => 'DAKOTA ROJOCOSTADP',
            'imagen' => 'assets/imagen/motos/DAKOTA ROJOCOSTADP.png',
            'cilindrada' => 250.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '28 HP a 9000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 13.0,
            'peso_neto' => 150,
            'carga_util' => 160,
            'peso_bruto' => 310,
            'largo' => 2020,
            'ancho' => 740,
            'alto' => 1120,
            'neumatico_delantero' => '100/80-17',
            'neumatico_posterior' => '140/70-17',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => true,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 5,
            'tipo_moto_id' => 5,
            'año' => 2024,
            'precio_base' => 5200.00,
            'color' => 'Rojo',
            'stock' => 8,
            'descripcion' => 'DAKOTA',
            'imagen' => 'assets/imagen/motos/DAKOTA.png',
            'cilindrada' => 300.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '32 HP a 8500 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 15.0,
            'peso_neto' => 170,
            'carga_util' => 180,
            'peso_bruto' => 350,
            'largo' => 2150,
            'ancho' => 780,
            'alto' => 1200,
            'neumatico_delantero' => '110/80-17',
            'neumatico_posterior' => '150/70-17',
            'freno_delantero' => 'Disco doble',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => true,
            'tablero_led' => true,
            'mp3' => true,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 6,
            'tipo_moto_id' => 4,
            'año' => 2024,
            'precio_base' => 3900.00,
            'color' => 'Azul',
            'stock' => 15,
            'descripcion' => 'Detroit azul',
            'imagen' => 'assets/imagen/motos/Detroit_azul.png',
            'cilindrada' => 200.0,
            'motor' => '4 tiempos OHC',
            'potencia' => '24 HP a 8000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '5 velocidades',
            'capacidad_tanque' => 12.0,
            'peso_neto' => 140,
            'carga_util' => 150,
            'peso_bruto' => 290,
            'largo' => 1980,
            'ancho' => 720,
            'alto' => 1100,
            'neumatico_delantero' => '90/90-17',
            'neumatico_posterior' => '130/70-17',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 7,
            'tipo_moto_id' => 4,
            'año' => 2024,
            'precio_base' => 2500.00,
            'color' => 'Azul',
            'stock' => 20,
            'descripcion' => 'Dretroit',
            'imagen' => 'assets/imagen/motos/Dretroit_3.png',
            'cilindrada' => 125.0,
            'motor' => '4 tiempos OHC',
            'potencia' => '12 HP a 7500 rpm',
            'arranque' => 'Eléctrico/Pedal',
            'transmision' => '5 velocidades',
            'capacidad_tanque' => 5.5,
            'peso_neto' => 95,
            'carga_util' => 130,
            'peso_bruto' => 225,
            'largo' => 1850,
            'ancho' => 680,
            'alto' => 1050,
            'neumatico_delantero' => '80/90-17',
            'neumatico_posterior' => '90/90-17',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Tambor',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => true,
            'tablero_led' => false,
            'mp3' => false,
            'bluetooth' => false,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 8,
            'tipo_moto_id' => 4,
            'año' => 2024,
            'precio_base' => 5500.00,
            'color' => 'Negro',
            'stock' => 12,
            'descripcion' => 'hummer de costado',
            'imagen' => 'assets/imagen/motos/hummer-de-costado.png',
            'cilindrada' => 400.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '42 HP a 9500 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 14.0,
            'peso_neto' => 165,
            'carga_util' => 170,
            'peso_bruto' => 335,
            'largo' => 2100,
            'ancho' => 760,
            'alto' => 1150,
            'neumatico_delantero' => '120/70-17',
            'neumatico_posterior' => '160/60-17',
            'freno_delantero' => 'Disco doble',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => true,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 9,
            'tipo_moto_id' => 2,
            'año' => 2024,
            'precio_base' => 4200.00,
            'color' => 'Plata Metálico',
            'stock' => 18,
            'descripcion' => 'hummer de costado',
            'imagen' => 'assets/imagen/motos/hummer-de-costado.png',
            'cilindrada' => 250.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '30 HP a 8800 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 14.5,
            'peso_neto' => 155,
            'carga_util' => 165,
            'peso_bruto' => 320,
            'largo' => 2050,
            'ancho' => 750,
            'alto' => 1180,
            'neumatico_delantero' => '100/80-17',
            'neumatico_posterior' => '140/70-17',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => true,
            'tablero_led' => true,
            'mp3' => true,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 1,
            'tipo_moto_id' => 2,
            'año' => 2024,
            'precio_base' => 3800.00,
            'color' => 'Rojo Racing',
            'stock' => 15,
            'descripcion' => 'moto deportiva ligera',
            'imagen' => 'assets/imagen/motos/deportiva_1.jpg',
            'cilindrada' => 200.0,
            'motor' => '4 tiempos SOHC',
            'potencia' => '24 HP a 8500 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '5 velocidades',
            'capacidad_tanque' => 12.0,
            'peso_neto' => 140,
            'carga_util' => 150,
            'peso_bruto' => 290,
            'largo' => 1950,
            'ancho' => 720,
            'alto' => 1100,
            'neumatico_delantero' => '90/80-17',
            'neumatico_posterior' => '120/70-17',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Tambor',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => false,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 2,
            'tipo_moto_id' => 2,
            'año' => 2024,
            'precio_base' => 2800.00,
            'color' => 'Azul Marino',
            'stock' => 22,
            'descripcion' => 'scooter urbano',
            'imagen' => 'assets/imagen/motos/deportiva_2.jpg',
            'cilindrada' => 125.0,
            'motor' => '4 tiempos OHC',
            'potencia' => '9.5 HP a 7500 rpm',
            'arranque' => 'Eléctrico y pedal',
            'transmision' => 'Automática CVT',
            'capacidad_tanque' => 6.5,
            'peso_neto' => 105,
            'carga_util' => 150,
            'peso_bruto' => 255,
            'largo' => 1850,
            'ancho' => 680,
            'alto' => 1150,
            'neumatico_delantero' => '90/90-12',
            'neumatico_posterior' => '100/90-10',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Tambor',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => true,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 3,
            'tipo_moto_id' => 2,
            'año' => 2024,
            'precio_base' => 6200.00,
            'color' => 'Verde Militar',
            'stock' => 10,
            'descripcion' => 'moto todo terreno',
            'imagen' => 'assets/imagen/motos/deportiva_3.jpg',
            'cilindrada' => 300.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '28 HP a 8000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 10.0,
            'peso_neto' => 135,
            'carga_util' => 160,
            'peso_bruto' => 295,
            'largo' => 2150,
            'ancho' => 820,
            'alto' => 1250,
            'neumatico_delantero' => '90/90-21',
            'neumatico_posterior' => '120/90-18',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Disco',
            'cargador_usb' => false,
            'luz_led' => true,
            'alarma' => false,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => false,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 4,
            'tipo_moto_id' => 6,
            'año' => 2024,
            'precio_base' => 7500.00,
            'color' => 'Negro Mate',
            'stock' => 8,
            'descripcion' => 'cruiser estilo clásico',
            'imagen' => 'assets/imagen/motos/deportiva_4.jpg',
            'cilindrada' => 650.0,
            'motor' => '4 tiempos V-Twin',
            'potencia' => '60 HP a 7000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '5 velocidades',
            'capacidad_tanque' => 16.0,
            'peso_neto' => 230,
            'carga_util' => 180,
            'peso_bruto' => 410,
            'largo' => 2300,
            'ancho' => 850,
            'alto' => 1100,
            'neumatico_delantero' => '120/70-19',
            'neumatico_posterior' => '170/80-15',
            'freno_delantero' => 'Disco doble',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => true,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 5,
            'tipo_moto_id' => 6,
            'año' => 2024,
            'precio_base' => 5800.00,
            'color' => 'Blanco Perlado',
            'stock' => 12,
            'descripcion' => 'deportiva de alto rendimiento',
            'imagen' => 'assets/imagen/motos/electrica_1.jpg',
            'cilindrada' => 500.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '48 HP a 9000 rpm',
            'arranque' => 'Eléctrico',
            'transmision' => '6 velocidades',
            'capacidad_tanque' => 15.0,
            'peso_neto' => 170,
            'carga_util' => 160,
            'peso_bruto' => 330,
            'largo' => 2100,
            'ancho' => 730,
            'alto' => 1150,
            'neumatico_delantero' => '110/70-17',
            'neumatico_posterior' => '150/60-17',
            'freno_delantero' => 'Disco doble',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 6,
            'tipo_moto_id' => 6,
            'año' => 2024,
            'precio_base' => 3200.00,
            'color' => 'Amarillo',
            'stock' => 20,
            'descripcion' => 'scooter eléctrico',
            'imagen' => 'assets/imagen/motos/electrica_2.jpg',
            'cilindrada' => 0.0,
            'motor' => 'Eléctrico 3000W',
            'potencia' => '15 HP equivalente',
            'arranque' => 'Eléctrico',
            'transmision' => 'Automática',
            'capacidad_tanque' => 0.0,
            'peso_neto' => 120,
            'carga_util' => 160,
            'peso_bruto' => 280,
            'largo' => 1900,
            'ancho' => 700,
            'alto' => 1100,
            'neumatico_delantero' => '100/80-14',
            'neumatico_posterior' => '110/80-14',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Disco',
            'cargador_usb' => true,
            'luz_led' => true,
            'alarma' => true,
            'cajuela' => true,
            'tablero_led' => true,
            'mp3' => true,
            'bluetooth' => true,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        DB::table('motos')->insert([
            'modelo_id' => 7,
            'tipo_moto_id' => 6,
            'año' => 2024,
            'precio_base' => 4900.00,
            'color' => 'Naranja',
            'stock' => 14,
            'descripcion' => 'motocross competición',
            'imagen' => 'assets/imagen/motos/electrica_3.jpg',
            'cilindrada' => 250.0,
            'motor' => '4 tiempos DOHC',
            'potencia' => '40 HP a 11000 rpm',
            'arranque' => 'Eléctrico y pedal',
            'transmision' => '5 velocidades',
            'capacidad_tanque' => 8.0,
            'peso_neto' => 110,
            'carga_util' => 120,
            'peso_bruto' => 230,
            'largo' => 2150,
            'ancho' => 825,
            'alto' => 1270,
            'neumatico_delantero' => '80/100-21',
            'neumatico_posterior' => '110/100-18',
            'freno_delantero' => 'Disco',
            'freno_posterior' => 'Disco',
            'cargador_usb' => false,
            'luz_led' => true,
            'alarma' => false,
            'cajuela' => false,
            'tablero_led' => true,
            'mp3' => false,
            'bluetooth' => false,
            'created_at' => $horaActual,
            'updated_at' => $horaActual,
        ]);

        
    }
}
